apiVersion: v1
kind: Service
metadata:
  name: mailpit-service
  labels:
    app: mailpit
spec:
  selector:
    app: mailpit
  ports:
    - protocol: TCP
      port: 8025
      targetPort: 8025
      name: http
    - protocol: TCP
      port: 1025
      targetPort: 1025
      name: smtp
  type: NodePort
