apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
data:
  APP_NAME: "ExcelJobber"
  APP_ENV: "test"
  APP_KEY: "base64:CMVCRPvuEKsuEKbYKoVSAJM6KUDK+WTgSrHi5wiUXe4="
  APP_DEBUG: "true"
  APP_TIMEZONE: "UTC"
  APP_URL: "http://localhost"
  APP_PORT: "8000"

  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"

  APP_MAINTENANCE_DRIVER: "file"
  APP_MAINTENANCE_STORE: "database"

  BCRYPT_ROUNDS: "12"

  LOG_CHANNEL: "stack"
  LOG_STACK: "single,stderr"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"

  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"

  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "database"

  CACHE_STORE: "database"
  CACHE_PREFIX: ""

  MEMCACHED_HOST: "127.0.0.1"

  REDIS_CLIENT: "phpredis"
  REDIS_HOST: "redis-service"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"

  VITE_APP_NAME: "ExcelJobber"
  MAIL_FROM_NAME: "ExcelJobber"
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
