apiVersion: v1
kind: Service
metadata:
  name: app-deploy-service
  labels:
    app: app-deploy-service
spec:
  type: ClusterIP
  ports:
    - name: http-app-deploy
      port: 80
      protocol: TCP
      targetPort: 80
#      nodePort: 30080
  selector:
    app: app-deploy

