apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-creator-sa
  namespace: excel

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator
  namespace: excel
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-binding
  namespace: excel
subjects:
  - kind: ServiceAccount
    name: job-creator-sa
    namespace: excel
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io


