---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.9.2
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false




# PASSWORD=$(kubectl get secret elasticsearch-es-elastic-user -o go-template='{{.data.elastic | base64decode}}')

# PASSWORD=RDsj0N590Lg0u04kCK56dW5Q

# curl -u "elastic:$PASSWORD" "https://localhost:63502/_search?q=message:Thanks for visiting devopscube"

# curl -u "elastic:$PASSWORD" -k "https://elasticsearch-es-http:9200"

# 63502

# curl -u "elastic:$PASSWORD" -k "https://localhost:63502"

# curl -k -u "elastic:RDsj0N590Lg0u04kCK56dW5Q" "https://localhost:63502/_search?q=message:HelloFluentd"
